[project]
name = "hiolib"
version = "0.1.0"
description = "Add your description here"
readme = "readme.org"
requires-python = ">=3.12"
dependencies = [
"hy==0.27.0",
"hyrule==0.4.0",
"pydantic==2.2.1",
"scapy",
"PyYAML",
"dnspython",
"yarl",
"pycryptodome",
"cryptography"
]
